# Generated by Django 3.2.9 on 2022-09-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220912_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
