# Generated by Django 3.2.9 on 2022-09-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220914_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='type',
            field=models.CharField(choices=[('SA', 'SA'), ('DOC', 'DOC'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=10),
        ),
    ]
