# Generated by Django 3.2.9 on 2022-09-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usermodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='type',
            field=models.CharField(choices=[('SA', 'SA'), ('DOC', 'DOC'), ('CUSTOMER', 'CUSTOMER')], default='DOC', max_length=10),
        ),
    ]
