# Generated by Django 3.2.9 on 2022-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_usermodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
