# Generated by Django 3.2.9 on 2022-09-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_usermodel_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User'},
        ),
    ]
