# Generated by Django 3.2.9 on 2022-10-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_usermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_agree',
            field=models.BooleanField(default=False),
        ),
    ]
