# Generated by Django 3.2.9 on 2022-10-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_usermodel_is_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
    ]
