# Generated by Django 3.2.9 on 2022-10-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_usermodel_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='qr_image',
        ),
    ]
