# Generated by Django 3.2.9 on 2022-10-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20221020_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvitedUser',
            new_name='InvitedDoctor',
        ),
    ]
