# Generated by Django 3.2.9 on 2022-09-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('d_o_b', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('last_answere', models.DateTimeField()),
                ('last_check_doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_saw_by', to='core.doctor')),
                ('recent_doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_see_dr', to='core.doctor')),
            ],
        ),
    ]
