# Generated by Django 3.2.9 on 2022-09-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220913_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_check_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_saw_by', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='recent_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_see_dr', to='core.doctor'),
        ),
    ]
