# Generated by Django 3.2.9 on 2022-09-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220913_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionWare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syptoms', models.JSONField(default=dict)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='patient_first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_check_doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='recent_doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_last_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctorobject'),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.questionware'),
            preserve_default=False,
        ),
    ]
