# Generated by Django 3.2.9 on 2022-09-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220914_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='details',
        ),
        migrations.RemoveField(
            model_name='appoinment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appoinment',
            name='patient',
        ),
        migrations.DeleteModel(
            name='DoctorObject',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
