# Generated by Django 3.2.9 on 2022-09-15 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20220914_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionWare',
            new_name='Questionire',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.usermodel'),
            preserve_default=False,
        ),
    ]
