# Generated by Django 3.2.9 on 2022-09-15 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20220915_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='account.usermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoinment',
            name='qs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.questionire'),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
