# Generated by Django 3.2.9 on 2022-10-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0005_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='username',
            new_name='last_name',
        ),
    ]
