# Generated by Django 3.2.9 on 2022-10-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0008_alter_qrcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
