# Generated by Django 3.2.9 on 2022-10-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0009_qrcode_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='user',
        ),
    ]
