# Generated by Django 3.2.9 on 2022-10-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0010_auto_20221020_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
