# Generated by Django 3.2.9 on 2022-10-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0011_alter_qrcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='image',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='url',
        ),
    ]
