# Generated by Django 3.2.9 on 2022-10-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0012_auto_20221025_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
