# Generated by Django 3.2.9 on 2022-10-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0013_auto_20221025_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='url',
            field=models.URLField(),
        ),
    ]
