# Generated by Django 3.2.9 on 2022-10-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0014_alter_qrcode_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='url',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
