# Generated by Django 3.2.9 on 2022-10-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0015_auto_20221026_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='name',
            field=models.URLField(),
        ),
    ]
