# Generated by Django 3.2.9 on 2022-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0019_auto_20221028_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
