# Generated by Django 3.2.9 on 2022-11-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0020_alter_appoinment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
